// foodIconMap.js template
// Place generated icons in: /assets/sprites/food/

const foodIconMap = {
  '梨': '/assets/sprites/food/food_pear.png',
  '山药': '/assets/sprites/food/food_yam.png',
  '芋头': '/assets/sprites/food/food_taro.png',
  '白萝卜': '/assets/sprites/food/food_radish.png',
  '花菜': '/assets/sprites/food/food_cauliflower.png',
  '上海青': '/assets/sprites/food/food_bok_choy.png',
  '大白菜': '/assets/sprites/food/food_napa_cabbage.png',
  '葡萄': '/assets/sprites/food/food_grape.png',
  '西瓜': '/assets/sprites/food/food_watermelon.png',
  '桃子': '/assets/sprites/food/food_peach.png',
  '猪里脊': '/assets/sprites/food/food_pork.png',
  '三文鱼': '/assets/sprites/food/food_salmon.png',
  '酸奶': '/assets/sprites/food/food_yogurt.png',
  '小米': '/assets/sprites/food/food_millet.png',
  '米粉': '/assets/sprites/food/food_rice_noodle.png',
  '生菜': '/assets/sprites/food/food_lettuce.png',
  '卷心菜': '/assets/sprites/food/food_cabbage_head.png',
  '芹菜': '/assets/sprites/food/food_celery.png',
  '芦笋': '/assets/sprites/food/food_asparagus.png',
  '苋菜': '/assets/sprites/food/food_amaranth.png',
  '豌豆苗': '/assets/sprites/food/food_pea_shoots.png',
  '竹笋': '/assets/sprites/food/food_bamboo_shoot.png',
  '西葫芦': '/assets/sprites/food/food_zucchini.png',
  '冬瓜': '/assets/sprites/food/food_wax_gourd.png',
  '苦瓜': '/assets/sprites/food/food_bitter_melon.png',
  '丝瓜': '/assets/sprites/food/food_loofah.png',
  '豌豆': '/assets/sprites/food/food_pea.png',
  '四季豆': '/assets/sprites/food/food_green_bean.png',
  '香菇': '/assets/sprites/food/food_shiitake.png',
  '金针菇': '/assets/sprites/food/food_enoki.png',
  '平菇': '/assets/sprites/food/food_oyster_mushroom.png',
  '海带': '/assets/sprites/food/food_kelp.png',
  '紫菜': '/assets/sprites/food/food_laver.png',
  '哈密瓜': '/assets/sprites/food/food_cantaloupe.png',
  '芒果': '/assets/sprites/food/food_mango.png',
  '木瓜': '/assets/sprites/food/food_papaya.png',
  '火龙果': '/assets/sprites/food/food_dragon_fruit.png',
  '樱桃': '/assets/sprites/food/food_cherry.png',
  '李子': '/assets/sprites/food/food_plum.png',
  '柚子': '/assets/sprites/food/food_grapefruit.png',
  '菠萝': '/assets/sprites/food/food_pineapple.png',
  '石榴': '/assets/sprites/food/food_pomegranate.png',
  '树莓': '/assets/sprites/food/food_raspberry.png',
  '羊肉': '/assets/sprites/food/food_lamb.png',
  '鸭肉': '/assets/sprites/food/food_duck.png',
  '火鸡肉': '/assets/sprites/food/food_turkey.png',
  '鲈鱼': '/assets/sprites/food/food_bass.png',
  '带鱼': '/assets/sprites/food/food_hairtail.png',
  '扇贝': '/assets/sprites/food/food_scallop.png',
  '蛤蜊': '/assets/sprites/food/food_clam.png',
  '鹌鹑蛋': '/assets/sprites/food/food_quail_egg.png',
  '豆浆': '/assets/sprites/food/food_soy_milk.png',
  '豆干': '/assets/sprites/food/food_dried_tofu.png',
  '毛豆': '/assets/sprites/food/food_edamame.png',
  '燕麦': '/assets/sprites/food/food_oat.png',
  '黑米': '/assets/sprites/food/food_black_rice.png',
  '藜麦': '/assets/sprites/food/food_quinoa.png',
  '荞麦': '/assets/sprites/food/food_buckwheat.png',
  '面粉': '/assets/sprites/food/food_wheat_flour.png',
  '馒头': '/assets/sprites/food/food_steamed_bun.png',
  '饺子': '/assets/sprites/food/food_dumpling.png',
  '蒸蛋羹': '/assets/sprites/food/food_egg_custard.png',
  '肉泥': '/assets/sprites/food/food_meat_puree.png',
};

module.exports = foodIconMap;
